### ISSUE TITLE
Dataset download requires an account

### ISSUE THREAD

**Issue by omniaalwazzan** [dazhangyu123/AEM#1]
Hi,

Many thanks for your work and for sharing your code and weights. Would it be possible for you to share a download link that does not require me to make an account?

Best regards, 
Omnia

**Comment by dazhangyu123** [comment]
Dear Omnia,

Thank you for your interest in our work and for reaching out about the code and weights.

I apologize for any inconvenience, but due to limited Google Drive capacity, I'm currently unable to share these datasets through that platform. At the moment, I can only provide access via Quark Netdisk, which does require an account.

I understand this may not be ideal, and I'm working on alternative solutions. In the near future, I plan to try sharing the extracted features through Baidu Netdisk, which might be more accessible.

I appreciate your patience and understanding. If you have any other questions or if there's anything else I can assist you with, please don't hesitate to ask.

Best regards,
Yunlong

**Comment by omniaalwazzan** [comment]
Hi Yunlong, 

Thanks a lot for your kind and detailed response. No worries, I understand this kind of situation. 

Best regards, 
Omnia.

**Comment by dazhangyu123** [comment]
I have updated dataset to huggingface. The url is: https://huggingface.co/datasets/dazhangyu123/AEM-dataset
